### ISSUE TITLE
Negative ranges don't apply

### ISSUE THREAD

**Issue by DarioSarra** [piever/ShiftedArrays.jl#15]
I had this issue trying to calculate a baseline activity in my signal. I stored my signal as the parent and the event I am interested in as the shifts. To normalise I need to calculate the mean of a time window 
before my event. 
`signal=collect(1:100);
event = ShiftedArray(v,-50);
shifted[-10:-5]
`
this throws the following error
`
BoundsError: attempt to access 100-element ShiftedArrays.ShiftedArray{Int64,Missings.Missing,1,Array{Int64,1}} at index [-10:-5]`

**Comment by piever** [comment]
Ups, forgot to overload `checkbounds` for `ShiftedArrays`, so it gives an unnecessary out of bounds error. Should be easy to fix.
