### ISSUE TITLE
Hosted Doc infrastructure

### ISSUE THREAD

**Issue by Nosferican** [piever/ShiftedArrays.jl#29]
Whenever I get a few mins I will open a Pr to go from README to Documenter hosted docs. Could you set up Documenter for the repo?

**Comment by piever** [comment]
I'm contemplating to reduce the scope of this package. My plan is to remove:
- The weird ad-hoc `reduce` method
- The methods to convert `Vector{ShiftedVector}` to a `Matrix` (dropping both dependencies of this package)
And then tag 1.0.0. 

Maybe it's better to wait for that to make proper documentation?

**Comment by Nosferican** [comment]
Sounds good.

**Comment by piever** [comment]
Closed by #34, but feel free to make doc PRs if you have improvements in mind!
